// If no preparation is required, remove all content from here

//==== Prepare your AWS account

//_Describe any setup required in the AWS account prior to template launch_

//==== Prepare your {partner-company-name} account

//_Describe any setup required in the partner portal/account prior to template launch_

:xrefstyle: short

== Prepare to deploy

Before you deploy the {partner-product-short-name} Quick Start, read the following sections so that you understand the choices that you'll need to make during deployment: deployment modes, dataflow options, and AMC drivers. Also follow all applicable instructions: enable AWS SSO, set up QuickSight, create an EC2 SSH key pair, etc.

=== Review the deployment modes

When you deploy the {partner-product-short-name} Quick Start, you choose between virtual and physical deployment modes.

* *Virtual deployment*. Virtual deployment is intended for demonstration, training, and evaluation of the {partner-product-short-name} Quick Start's capabilities. You launch EC2 instances to simulate edge gateway hardware. In all other respects, the virtual architecture mirrors that of the physical deployment. Virtual mode relies on simulated tag values generated by the partner edge software. No physical PLCs or sensors are connected.
* *Physical deployment*. With physical deployment, you deploy edge software (such as AWS IoT Greengrass and partner edge software) on physical industrial PCs that are ready to connect to physical devices (such as PLCs or historians or SCADA systems) on the customer's factory floor. The physical deployment has two types: greenfield and brownfield.
** *Greenfield.* In a greenfield physical deployment, you build from scratch for a new environment. AWS IoT Greengrass and the partner edge software run on a single edge device (an industrial PC) with Ignition installed alongside AWS IoT Greengrass on the same PC.
** *Brownfield.* In a brownfield physical deployment, you build within an existing environment. AWS IoT Greengrass runs standalone on an industrial PC and connects to the partner edge software application that is already running on the customer's premises, such as on a virtual machine in the server room of a factory. Assume that your access to the hardware is limited or nonexistent and that your ability to reconfigure the edge software application server is limited to additive changes only.

=== Review the dataflow options

When you deploy the {partner-product-short-name} Quick Start, you choose between three dataflow options. Each option ingests data differently from the edge environment into the AWS Cloud. 

* *Option 1 (OPC UA to AWS IoT SiteWise).* With this option, you configure the AWS IoT Greengrass SiteWise connector to connect to the edge software application OPC UA server. All telemetry data flows directly into AWS IoT SiteWise.
* *Option 2a (MQTT to AWS IoT Core).* With this option, the edge software application server connects to AWS IoT Core from MQTT. All telemetry data is pushed from the edge software application server to AWS IoT Core. From there, the data is pushed to Amazon S3 or a similar data lake for processing. Data is not forwarded to AWS IoT SiteWise. Custom development is required to populate data in AWS IoT SiteWise.
* *Option 2b (MQTT to AWS IoT Greengrass to AWS IoT Core).* This option is identical to 2a except that the edge software application server pushes MQTT data messages to AWS IoT Greengrass core first. Then those messages are forwarded to AWS IoT Core. Data is not forwarded to AWS IoT SiteWise. Custom development is required to populate data in AWS IoT SiteWise.

For physical deployments, you will use one of the following bootup scripts during the post-deployment steps to configure both the deployment type and the dataflow option.
 
* BootupScriptGreenfieldOption1 (greenfield deployment, dataflow option 1)
* BootupScriptGreenfieldOption2a (greenfield deployment, dataflow option 2a)
* BootupScriptGreenfieldOption2b (greenfield deployment, dataflow option 2b)
* BootupScriptBrownfieldAllOptions (brownfield deployment, any dataflow option)

=== Review the AMC drivers
When you deploy the {partner-product-short-name} Quick Start, you choose an AMC driver. This driver determines which edge software application the {partner-product-short-name} Quick Start connects to AWS IoT SiteWise. You can choose any of three AMC drivers: IgnitionCirrusLink, IgnitionFileExport, or KepwareFileExport.

* *IgnitionCirrusLink*. This AMC driver uses the Cirrus Link transmission module running on Ignition to publish birth certificates for all devices defined with Ignition's tag database. This module follows the Sparkplug version B specification for MQTT. This AMC driver runs automatically during the {partner-product-short-name} Quick Start deployment, so AWS IoT SiteWise resources are created automatically when the {partner-product-short-name} Quick Start is deployed. In the AWS CloudFormation stack `AMCDriver` parameter, you will choose *IgnitionCirrusLink*.

* *IgnitionFileExport*. This AMC driver uses the manual tag definition file-export mechanism within Ignition. With this AMC driver option, during the post-deployment steps, users manually export the tag definition file and upload it to an S3 bucket to initiatve the AMC process. In the AWS CloudFormation stack `AMCDriver` parameter, you will choose *IgnitionFileExport*.

* *KepwareFileExport*. This AMC driver uses the manual tag definition file-export mechanism within Kepware. With this AMC driver option, during the post-deployment steps, you manually export the tag definition file and upload it to an S3 bucket to initiate the AMC process. In the AWS CloudFormation stack `AMCDriver` parameter, you will choose *KepwareFileExport*.

=== Enable AWS SSO
If AWS Single Sign-On (AWS SSO) has not already been enabled in the Region where you are launching the AWS CloudFormation stack, enable it as follows.

. Sign in to your AWS account at https://aws.amazon.com with an IAM user role that has the necessary permissions.
. Sign in to the AWS Console, and open the AWS SSO service. Make sure that you are in the Region where you are launching the AWS CloudFormation stack.
. Choose *Enable AWS SSO*.
. If you don't have an AWS organization set up for your account (as required for AWS SSO usage), you'll be prompted to create one. Choose *Create AWS organization*. For more information, see the https://docs.aws.amazon.com/singlesignon/latest/userguide/getting-started.html[Getting Started^] page in the AWS SSO documentation.
. Create an AWS SSO group.
.. Open the AWS SSO service in the AWS Console.
.. Choose *Groups* in the navigation bar. 
.. If no groups exist, choose *Create group*.
.. Give the group a name and choose *Create*.
. Create an AWS SSO user.
.. Open the AWS SSO service in the AWS Console.
.. Choose *Users* in the navigation bar.
.. Choose *Add user*.
.. Provide a user name, and fill out the remaining fields.
.. Choose *Next, Groups*.
.. Choose a group, and then choose *Add user*. The AWS SSO user is now active. This user will be able to access the SiteWise Monitor dashboards, as described in the final part of the {partner-product-short-name} Quick Start launch procedure.

=== Set up QuickSight

. Open the QuickSight console, and choose *Sign up for QuickSight*.
. Choose an edition: *Standard* or *Enterprise*.
. Choose the AWS Region that you plan to deploy the {partner-product-short-name} Quick Start into. QuickSight is now enabled and is ready for use.

=== Create an EC2 SSH key pair
If you do not already have an EC2 SSH (Secure Shell) key pair available (PEM file format), create one in the Region where you are launching the AWS CloudFormation stack. For instructions, see https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html[Amazon EC2 key pairs and Linux instances^].

=== Create an AWS IoT SiteWise service-linked role 
Run the following command from the AWS CLI:

 +aws iam create-service-linked-role --aws-service-name iotsitewise.amazonaws.com --description "Service-linked role to support IoT SiteWise"+

For more information about creating service-linked-roles, see https://docs.aws.amazon.com/iot-sitewise/latest/userguide/using-service-linked-roles.html[Using service-linked roles for AWS IoT SiteWise^].

=== Connect to the edge hardware (physical deployments only)
For physical deployments, connect to the edge hardware as follows:

. Connect to your hardware running Ubuntu 18.04. 
. Ensure that you can connect to the internet. 
. Using either an SSH command or a connection to the device with a keyboard and monitor, configure the AWS CLI on the hardware to communicate with the AWS account you plan to deploy in. For details, see https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html[Configuring the AWS CLI^].
. Ensure that the directory structure of the hardware running Ubuntu 18.04 looks like this:
....
home/
    ubuntu
....

[start=5]
. For physical-brownfield deployments with Ignition, ensure that you are using these minimum software versions:
* Ignition: 8.0.12
* Cirrus Link MQTT transmission module: 4.0.4-SNAPSHOT (b2020051210)
