//This document is the ASCII DOC version of the "IMC - Virtual Deployment User Guide" word document found in the IMC Quick Start Github repo (URL: https://github.com/aws-quickstart/quickstart-aws-industrial-machine-connectivity/blob/master/documentation/IMC%20-%20Virtual%20Deployment%20User%20Guide.docx)

=== Virtual deployment guide

==== Introduction
The virtual deployment is intended for demonstration, training, and evaluation of the {partner-product-short-name} Quick Start's capabilities. EC2 instances are launched to simulate edge gateway hardware. In all other respects, the experience mirrors that of the physical deployment. Virtual-deployment mode relies on simulated tag values that are generated by the partner edge software. No physical PLCs or sensors are being connected.

==== Deployment options
The options for virtual deployment depend on two configuration choices:

. Dataflow option - There are three options for dataflow:
- Option 1
- Option 2a
- Option 2b
. Ignition tag hierarchy source
- Cirrus Link MQTT module: This option is based on the Cirrus Link MQTT transmission module implementing the SparkplugB MQTT spec to publish birth certificates when a node or device is created within the Ignition Designer UI dashboard. The AMC runs automatically without a manual step with this option and results in assets provisioned within AWS IoT SiteWise.
- Ignition File Export - This option is based on exporting a JSON tag hierarchy definition file from Ignition Server and uploading it into an S3 bucket. After the file is uploaded to the S3 bucket, the AMC runs automatically, resulting in assets provisioned within AWS IoT SiteWise.

Depending on the choices of these two configuration options, there are a total of six deployment modes:

. Virtual Option 1 Cirrus Link MQTT module 
. Virtual Option 1 Ignition File Export  
. Virtual Option 2a Cirrus Link MQTT module
. Virtual Option 2a Ignition File Export
. Virtual Option 2b Cirrus Link MQTT module 
. Virtual Option 2b Ignition File Export

==== Getting started

. Make sure that you have completed the prerequisites detailed in the link:pre-reqs.adoc[Prepare for Deployment] section.
//TODO Marcia: verify this link above and others like it throughout.
. Make sure that you are launching the AWS CloudFormation stack in one of the supported Regions for the {partner-product-short-name} Quick Start. For the choices, see link:#_supported_regions[Supported Regions] earlier in this guide.

. Choose one of the six deployment modes from the *Deployment Modes* list earlier, and follow these sections:
.. AWS CloudFormation stack launch
.. Post-deployment steps

==== References:
Refer to the following sections as needed:

- Troubleshooting - Refer to this section to troubleshoot {partner-product-short-name} stack launch and operation.
- Virtual Cleanup - Refer to this section to cleanup AWS resources launched for the {partner-product-short-name} Quick Start.
- Virtual Deployment FAQ - Refer to this section for FAQs regarding {partner-product-short-name} Quick Start.

==== Launch the AWS CloudFormation stack
To launch the virtual deployment of the {partner-product-short-name} Quick Start, sign in to the AWS Console, and open the AWS CloudFormation console. Create a new stack, and choose *with new resources (standard)*. 

===== Step 1: Specify templates

* Prerequisites:
** Choose *Template is ready*.
* Choose one of the following templates:
** Template source: Leave as default – *Amazon S3 URL*. Most users want to use the `IMC-master.template.yaml` main template that's in the AWS Quick Start S3 bucket. 
*** Main template S3 URL: https://aws-quickstart.s3.amazonaws.com/quickstart-aws-industrial-machine-connectivity/templates/IMC-master.template.yaml
*** This template launches the Quick Start in a new VPC. Only five VPCs per account are permitted. 
** Alternatively, launch the `IMC-workload.template.yaml` AWS Cloudformation template. The workload template launches the Quick Start in your default VPC. 
*** Workload template S3 URL: https://aws-quickstart.s3.amazonaws.com/quickstart-aws-industrial-machine-connectivity/templates/IMC-workload.template.yaml
* Choose *Next* to proceed to Step 2: Specify stack details.

===== Step 2 – Specify stack details (if using the main template)

* Stack name: 
** Stack name: Give the stack a unique name such as *IMC-Virtual*.
* Parameters
** Network configuration
*** VPC CIDR: Defaults to 10.0.0.0/16. Change if desired.
	Public subnet 1 CIDR: Defaults to 10.0.128.0/20. Change if desired.
	VPC Tenancy: Defaults to nondedicated. Change if desired.
o	AWS Quick Start Configuration
	QuickStart S3 Bucket Name: aws-quickstart
	QuickStart S3 Key Prefix: quickstart-aws-industrial-machine-connectivity/
	QuickStart S3 Bucket Region: Suggested to leave as default "us-east-1"
o	Edge Deployment Configuration
	Name for the edge device: You may leave as default or, if desired, you may specify a new name for the edge device. This is the name of the AWS IoT Greengrass group that gets created with this stack.
	Type of Deployment (virtual or physical): virtual
	Deployment Flow: Choose *Option 1*. 

o	Amazon EC2 configuration
	SSH key name: Choose your SSH key name (EC2 key pair). This is the key pair used to SSH into the EC2 instances and bootstrap the partner edge software application and AWS IoT Greengrass, respectively.
	AWS IoT Greengrass EC2 instance type: (default: t3.small) You can choose a larger (t3.medium) instance if desired. It is suggested you leave the as the default value.
	Ignition EC2 instance types: (default: t3.large) You can choose a larger (t3.xlarge) instance if desired. It is suggested you leave the as the default value.
	Choose the Asset Model Converter (AMC) driver: Leave as default (`IgnitionCirrusLink`). 
	User public IP address: Input your public IP address in the format `x.x.x.x` so the EC2 instance security groups allow access from your IP address.

//TODO Marcia: Is this Step 2 duplicating what's in our parameter tables?

.TABLE DESCRIPTION
|===
|Parameter label (name) |Default Value |Description

// Space needed to maintain table headers
|VPC CIDR |10.0.0.0/16 |TEST
|X |X |X
|X |X |X
|X |X |X


|===

